# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Book.destroy_all

Book.create(isbn: "9783736802193", title: "The Brothers Karamazov", description:"The Brothers Karamazov is the final novel by the Russian author Fyodor Dostoyevsky. The Brothers Karamazov is a passionate philosophical novel set in 19th century Russia, that enters deeply into the ethical debates of God, free will, and morality. It is a spiritual drama of moral struggles concerning faith, doubt, and reason, set against a modernizing Russia. Dostoyevsky composed much of the novel in Staraya Russa, which inspired the main setting. Since its publication, it has been acclaimed as one of the supreme achievements in literature. The Brothers Karamazov displays a number of modern elements. Dostoyevsky composed the book with a variety of literary techniques. Though privy to many of the thoughts and feelings of the protagonists, the narrator is a self-proclaimed writer; he discusses his own mannerisms and personal perceptions so often in the novel that he becomes a character. Through his descriptions, the narrator's voice merges imperceptibly into the tone of the people he is describing, often extending into the characters' most personal thoughts. In addition to the principal narrator there are several sections narrated by other characters entirely, such as the story of the Grand Inquisitor and Zosima's confessions. This technique enhances the theme of truth, making many aspects of the tale completely subjective.", image_link: "http://books.google.com/books/content?id=xyRqAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Fyodor Dostoyevsky")
Book.create(isbn: "9780241355121", title: "Day of the Oprichnik", description: "Haunting, terrifying and hilarious, The Day of the Oprichnik is a dazzling novel and a fierce critique of life in the New Russia Moscow 2028: Andrei Danilovich Komiaga, oprichnik, member of the czar's inner circle of trusted courtiers, rouses himself from a drunken stupor and prepares for another day of debauchery, violence, terror and beauty. In this New Russia, futuristic technology combine with the draconian world of Ivan the Terrible to create a dystopia chillingly akin to reality. Over the twenty-four-hour span of the novel, Komiaga will rape, pillage and torture, in the name of the czar he fears and adores. Shimmering with invention, fierce social commentary and razor-sharp wit, Day of the Oprichnik imagines a near future too disturbing to contemplate and too close to reality to ignore.", image_link: "http://books.google.com/books/content?id=cINbDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Vladimir Sorokin")
Book.create(isbn: "9780199536368", title: "Crime and Punishment", description: "Richard Peace is Emeritus Professor of Russian at Bristol University. He is the author of Dostoevsky: An Examination of his Major Novels.", image_link: "http://books.google.com/books/content?id=V74UDAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Fyodor Dostoevsky, Jessie Coulson")
Book.create(isbn: "9780143038405", title: "The Dream Life of Sukhanov", description: "After losing his job and the respect of his family, Russian avant-garde artist Anatoly Sukhanov confronts his past in a series of dreams that reveals the sacrifices he has made to gain material wealth in twentieth-century Moscow. A first novel. Reprint. 40,000 first printing.", image_link: "http://books.google.com/books/content?id=4mMCgzdbwOYC&printsec=frontcover&img=1&zoom=1&source=gbs_api", authors: "Olga Grushin")
Book.create(isbn: "9780486114422", title: "Anna Karenina", description: "A tumultuous tale of passion and self-discovery in 1870s Russia chronicles a society woman's adulterous affair and a landowner's unconventional quest for a meaningful existence.", image_link: "http://books.google.com/books/content?id=dm8fqg9B8DEC&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Leo Tolstoy")
Book.create(isbn: "9781681371733", title: "The Slynx", description: "“A postmodern literary masterpiece.” –The Times Literary Supplement Two hundred years after civilization ended in an event known as the Blast, Benedikt isn’t one to complain. He’s got a job—transcribing old books and presenting them as the words of the great new leader, Fyodor Kuzmich, Glorybe—and though he doesn’t enjoy the privileged status of a Murza, at least he’s not a serf or a half-human four-legged Degenerator harnessed to a troika. He has a house, too, with enough mice to cook up a tasty meal, and he’s happily free of mutations: no extra fingers, no gills, no cockscombs sprouting from his eyelids. And he’s managed—at least so far—to steer clear of the ever-vigilant Saniturions, who track down anyone who manifests the slightest sign of Freethinking, and the legendary screeching Slynx that waits in the wilderness beyond. Tatyana Tolstaya’s The Slynx reimagines dystopian fantasy as a wild, horripilating amusement park ride. Poised between Nabokov’s Pale Fire and Burgess’s A Clockwork Orange, The Slynx is a brilliantly inventive and shimmeringly ambiguous work of art: an account of a degraded world that is full of echoes of the sublime literature of Russia’s past; a grinning portrait of human inhumanity; a tribute to art in both its sovereignty and its helplessness; a vision of the past as the future in which the future is now.", image_link: "http://books.google.com/books/content?id=nRJyDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Tatyana Tolstaya")
Book.create(isbn: "9782291008170", title: "The Death of Ivan Ilych", description: "The Death of Ivan Ilyich was first published in 1886. 
It is a novella by Leo Tolstoy. It is one of Tolstoy's most celebrated pieces of late fiction. This work stems in part from Tolstoy's anguished intellectual and spiritual struggles which led to his conversion to Christianity. Central to the story is an examination on the nature of both life and death, and how man can come to terms with death's very inevitability. The novella was acclaimed by Vladimir Nabokov and Mahatma Gandhi as the greatest in the whol", image_link: "http://books.google.com/books/content?id=-8OJDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Leo Tolstoy")
Book.create(isbn: "9781681951713", title: "Dead Souls", description: "A Masterpiece of Social and Political Commentary “Howe
ver stupid a fools words may be, they are sometimes enough to confound an intelligent man.” ― Nikolai Gogol, Dead Souls In Nikolai Gogo's Dead Souls, a middle class man seeks to use a loophole in the Russian feudal system to create a fortune. This Xist Classics edition has been professionally formatted for e-readers with a linked table of contents. This eBook also contains a bonus book club leadership guide and discussion questions. We hope you’ll share this book with your friends, neighbors and colleagues and can’t wait to hear what you have to say about it.", image_link: "http://books.google.com/books/content?id=C-QmCwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Nikolai Gogol")
Book.create(isbn: "9781783193981", title: "The Master and Margarita", description: "A mysterious stranger appears in a Moscow park. Soon he and his retinue have astonished the locals with the magic show to end all magic shows. But why are they really here, and what has it got todo with the beautiful Margarita, or her lover, the Master, a silenced writer? A carnival for the senses and a diabolical extravaganza, this most exuberant of Russian novels was staged in this adaptation at Chichester Festival Theatre.", image_link: "http://books.google.com/books/content?id=-zI2DwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Mikhail Bulgakov, Edward Kemp")
Book.create(isbn: "9781853262869", title: "Fathers and Sons", description: "With an Introduction by Lionel Kelly, University of Reading. Translated by C.J. Hogarth. Fathers and Sons is one of the greatest nineteenth century Russian novels, and has long been acclaimed as Turgenev's finest work. It is a political novel set in a domestic context, with a universal theme, the generational divide between fathers and sons. Set in 1859 at the moment when the Russian autocratic state began to move hesitantly towards social and political reform, the novel explores the conflict between the liberal-minded fathers of Russian reformist sympathies and their free-thinking intellectual sons whose revolutionary ideology threatened the stability of the state. At its centre is Evgeny Bazorov, a strong-willed antagonist of all forms of social orthodoxy who proclaims himself a nihilist and believes in the need to overthrow all the institutions of the state. As the novel develops Bazarov's political ambitions become fatally meshed with emotional and private concerns, and his end is a tragic failure. The novel caused a bitter furore on its publication in 1862, and this, a year later, drove Turgenev from Russia.", image_link: "http://books.google.com/books/content?id=5x3HM34XBFQC&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Ivan Sergeevich Turgenev")
Book.create(isbn: "9780241284414", title: "And Quiet Flows the Don", description: "'A wonderful, unsparing epic ... an intimate human story of loss and love' New Statesman, Books of the Year The epic novel of love, war and revolution from Mikhail Sholokhov, winner of the Nobel Prize in Literature An extraordinary Russian masterpiece, And Quiet Flows the Don follows the turbulent fortunes of the Cossack people through peace, war and revolution - among them the proud and rebellious Gregor Melekhov, who struggles to be with the woman he loves as his country is torn apart. Borne of Mikhail Sholokhov's own early life in the lands of the Cossacks by the river Don, it is a searing portrait of a nation swept up in conflict, with all the tragic choices it brings.", image_link: "http://books.google.com/books/content?id=nRJyDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=none&source=gbs_api", authors: "Mikhail Sholokhov")